version: "3"

services:
  backend:
    build: ./server
    ports:
      - "3000:3000"
    env_file:
      - ./server/.env

  frontend:
    build: ./client
    ports:
      - "5173:80"
    depends_on:
      - backend